blank_issues_enabled: false
contact_links:
  - name: WordPress.org Support Forum
    url: https://wordpress.org/support/plugin/google-calendar-widget/
    about: Please ask and answer questions here.
  - name: Security Vulnerability
    url: https://github.com/thomasvincent/google-calendar-widget/security/policy
    about: Please report security vulnerabilities here.
