name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --no-progress
          npm ci

      - name: Run tests
        run: |
          npm test
          composer test

      - name: Build plugin
        run: |
          mkdir -p build/google-calendar-widget
          cp -r *.php *.css *.js *.txt *.md languages examples build/google-calendar-widget/
          cp -r assets build/google-calendar-widget/ || true
          cd build
          zip -r google-calendar-widget.zip google-calendar-widget

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/google-calendar-widget.zip
          asset_name: google-calendar-widget-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
