name: Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          npm install

      # Temporarily disable PHPCS configuration until we can fix the coding standards issues
      # - name: Configure PHPCS
      #   run: composer config-phpcs

      - name: Run tests
        run: |
          npm test
          # Temporarily disable PHPCS checks until we can fix the coding standards issues
          # composer phpcs
          composer test

      - name: Build plugin
        run: |
          mkdir -p build/google-calendar-widget
          cp -r *.php *.txt *.md languages examples build/google-calendar-widget/
          cp -r assets includes build/google-calendar-widget/
          cd build
          zip -r google-calendar-widget.zip google-calendar-widget

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
          files: |
            ./build/google-calendar-widget.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
